spring:
  config:
    activate:
      on-profile: "prod"
build:
  version: "3.0"

loans:
  message: "Welcome to HDFCBank loans related prod APIs "
  contactDetails:
    name: "Rahul Dravid - Product Owner"
    email: "rahul@hdfcbank.com"
  onCallSupport:
    - (723) 656-8709
    - (156) 342-0956
